host: localhost
database: serveur
username: default
password: default

redis-host: localhost
redis-port: 6379
redis-password: default
redis-client: default

player: fr.leconsulat.api.player.ConsulatPlayer
debug: false
dev: false
server-name: unknown